package com.fengmap.kotlindemo.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_INFO".
*/
public class NewsInfoDao extends AbstractDao<NewsInfo, Long> {

    public static final String TABLENAME = "NEWS_INFO";

    /**
     * Properties of entity NewsInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Url = new Property(3, String.class, "url", false, "URL");
        public final static Property Thumbnail_pic_s = new Property(4, String.class, "thumbnail_pic_s", false, "THUMBNAIL_PIC_S");
        public final static Property Thumbnail_pic_s3 = new Property(5, String.class, "thumbnail_pic_s3", false, "THUMBNAIL_PIC_S3");
        public final static Property Thumbnail_pic_s2 = new Property(6, String.class, "thumbnail_pic_s2", false, "THUMBNAIL_PIC_S2");
        public final static Property IsChoose = new Property(7, boolean.class, "isChoose", false, "IS_CHOOSE");
    };


    public NewsInfoDao(DaoConfig config) {
        super(config);
    }
    
    public NewsInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"DATE\" TEXT," + // 2: date
                "\"URL\" TEXT," + // 3: url
                "\"THUMBNAIL_PIC_S\" TEXT," + // 4: thumbnail_pic_s
                "\"THUMBNAIL_PIC_S3\" TEXT," + // 5: thumbnail_pic_s3
                "\"THUMBNAIL_PIC_S2\" TEXT," + // 6: thumbnail_pic_s2
                "\"IS_CHOOSE\" INTEGER NOT NULL );"); // 7: isChoose
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewsInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(4, url);
        }
 
        String thumbnail_pic_s = entity.getThumbnail_pic_s();
        if (thumbnail_pic_s != null) {
            stmt.bindString(5, thumbnail_pic_s);
        }
 
        String thumbnail_pic_s3 = entity.getThumbnail_pic_s3();
        if (thumbnail_pic_s3 != null) {
            stmt.bindString(6, thumbnail_pic_s3);
        }
 
        String thumbnail_pic_s2 = entity.getThumbnail_pic_s2();
        if (thumbnail_pic_s2 != null) {
            stmt.bindString(7, thumbnail_pic_s2);
        }
        stmt.bindLong(8, entity.getIsChoose() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewsInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(4, url);
        }
 
        String thumbnail_pic_s = entity.getThumbnail_pic_s();
        if (thumbnail_pic_s != null) {
            stmt.bindString(5, thumbnail_pic_s);
        }
 
        String thumbnail_pic_s3 = entity.getThumbnail_pic_s3();
        if (thumbnail_pic_s3 != null) {
            stmt.bindString(6, thumbnail_pic_s3);
        }
 
        String thumbnail_pic_s2 = entity.getThumbnail_pic_s2();
        if (thumbnail_pic_s2 != null) {
            stmt.bindString(7, thumbnail_pic_s2);
        }
        stmt.bindLong(8, entity.getIsChoose() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NewsInfo readEntity(Cursor cursor, int offset) {
        NewsInfo entity = new NewsInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // thumbnail_pic_s
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // thumbnail_pic_s3
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // thumbnail_pic_s2
            cursor.getShort(offset + 7) != 0 // isChoose
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewsInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setThumbnail_pic_s(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setThumbnail_pic_s3(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setThumbnail_pic_s2(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsChoose(cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NewsInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NewsInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
